global:
  scrape_interval:     30s
  evaluation_interval: 30s
  scrape_timeout: 15s


scrape_configs:
  - job_name: 'gitlab-ci-pipelines-exporter'
    scrape_interval: 30s
    scrape_timeout: 15s
    static_configs:
      - targets: ['gitlab-ci-pipelines-exporter:8080']
