{
 "title": "DASHBOARD CI/CD v2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "agrupador",
    "label": "projeto",
    "query": {
     "query": "label_values(gitlab_ci_environment_information,project)"
    }
   },
   { "name": "branch", "label": "Branch Name", "query": ".*" },
   {
    "name": "projeto",
    "label": "repositorio",
    "query": {
     "query": "label_values(gitlab_ci_environment_information{project=~\"$projeto.*\"},project)"
    }
   },
   {
    "name": "ENVIRONMENT",
    "label": "ENVIRONMENT",
    "query": {
     "query": "label_values(gitlab_ci_environment_information{project=~\"$projeto\"},environment)"
    }
   },
   { "name": "GITLAB_HOST", "label": "GITLAB_HOST", "query": "gitlab.ourinvest.com.br" }
  ]
 },
 "panels": [
  {
   "title": "GITLAB EXPORTER STATUS #",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"gitlab-ci-pipelines-exporter\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 15, "x": 3, "y": 0 },
   "options": {
    "content": "<h1>Dashboard CI/CD Gitlab</h1>\n<p style=\"text-align:left;\"><img src=\"https://www.cloudfoundry.org/wp-content/uploads/2017/10/icon_gitlab_cf@2x.png\" width=80px/></p>\n<div style=\"text-align: left;\">\n  <img src=\"https://cdn.prod.website-files.com/65172cb208ef8ecb7765b47f/65325415b94c8eb794a07d00_brand_white.svg\" loading=\"lazy\" alt=\"brand image\" />\n</div>"
   }
  },
  {
   "title": "TOTAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "JOBS TOTAL #",
     "type": "stat",
     "description": "Exibe o número total de jobs nos projetos especificados.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(gitlab_ci_pipeline_job_run_count{project=~\"${projeto}\", ref=~\"${branch}\"})"
      }
     ]
    },
    {
     "title": "JOBS FALHAS #",
     "type": "stat",
     "description": "Exibe o número total de jobs que falharam.",
     "gridPos": { "h": 5, "w": 2, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status)(\r\n  gitlab_ci_pipeline_job_status{project=~\"${projeto}.*\",status=\"failed\", ref=~\"${branch}\"}\r\n)"
      }
     ]
    },
    {
     "title": "PIPELINES TOTAL #",
     "type": "stat",
     "description": "Exibe o número total de pipelines executadas.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(gitlab_ci_pipeline_run_count{project=~\"${projeto}\", ref=~\"${branch}\"})"
      }
     ]
    },
    {
     "title": "PIPELINES FALHAS #",
     "type": "stat",
     "description": "Exibe o número de pipelines que falharam.",
     "gridPos": { "h": 5, "w": 2, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(gitlab_ci_pipeline_status{status=\"failed\", project=~\"${projeto}\", ref=~\"${branch}\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "PIPELINES TOTAL #",
     "type": "stat",
     "description": "Exibe o número total de pipelines executadas.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\r\n  gitlab_ci_environment_deployment_status{project=~\"${projeto}\", environment=~\"${ENVIRONMENT}.*\"} \r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "DEPLOYS FALHAS #",
     "type": "stat",
     "description": "Exibe o número de pipelines que falharam.",
     "gridPos": { "h": 5, "w": 2, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\r\n  gitlab_ci_environment_deployment_status{project=~\"${projeto}\", environment=~\"${ENVIRONMENT}.*\", status=\"failed\"} \r\n) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "DOC #",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "DOC #",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "#  <span style=\"color:black\">Dashboard CI/CD GitLab</span>\n\nEste Dashboard foi desenvolvido para fornecer uma visão abrangente das operações de CI/CD no ambiente do GitLab. Ele permite identificar rapidamente problemas em pipelines, analisar a eficiência de builds e releases, e monitorar o desempenho de jobs. Com isso, a companhia pode melhorar a qualidade das entregas, reduzir o tempo de desenvolvimento e mitigar riscos associados a falhas em deploys, garantindo um processo de entrega contínua mais robusto e eficiente.\n\n## <span style=\"color:red\">Variáveis</span>\n\n### Variável de Projeto\n- **Nome:** `projeto`\n- **Descrição:** Esta variável é preenchida automaticamente com os nomes dos projetos do GitLab disponíveis. Ela permite que você filtre os dados exibidos no dashboard para um ou mais projetos específicos.\n- **Comportamento:** A variável `projeto` é usada em diversas métricas do dashboard para segmentar as visualizações por projeto. É possível selecionar múltiplos projetos ou todos os projetos, utilizando o valor padrão `$__all`.\n\n### Variável de Repositório\n- **Nome:** `repositorio`\n- **Descrição:** Filtra os dados por repositório no GitLab.\n- **Comportamento:** Usada para selecionar os repositórios e aplicar nas métricas dos dashboards.\n\n### Variável de Environment\n- **Nome:** `ENVIRONMENT`\n- **Descrição:** Filtra os dados exibidos no dashboard por environments específicos (Deployments realizados utilizando enviroments).\n- **Comportamento:** Pode-se selecionar múltiplos environments ou um único, dependendo da análise desejada. Esse campo é importante para avaliar as entregas que utilizam enviroments do Gitlab.\n\n### Variável de Filtro Branch\n- **Nome:** `branch`\n- **Descrição:** Esta variável permite filtrar os dados exibidos no dashboard por branches específicas. Por padrão, o valor é \".*\", o que significa que todas as branches serão consideradas.\n- **Uso:** \n  - Para visualizar dados de uma branch específica, como `master`, basta digitar `master`.\n  - Para visualizar todas as branches que começam com um determinado prefixo, como `master`, utilize a expressão `master.*`.\n  - O valor padrão \".*\" coleta todas as branches, permitindo uma visão abrangente das operações CI/CD em todas as branches.\n\n## <span style=\"color:red\">Categorias</span>\n\n### <span style=\"color:yellow\">1. JOBS \\#</span>\n\n#### 1.1 JOBS TOTAL #\n- **Descrição:** Exibe o número total de jobs nos projetos especificados.\n- **Interpretação:** Um número elevado de jobs pode indicar uma alta carga de trabalho nos pipelines, o que pode impactar os recursos do sistema.\n\n#### 1.2 JOBS FALHAS #\n- **Descrição:** Exibe o número total de jobs que falharam.\n- **Interpretação:** Um alto número de falhas pode sugerir problemas nos scripts ou na configuração dos jobs.\n\n#### 1.3 JOBS POR PERÍODO #\n- **Descrição:** Exibe o número de jobs executados em um período específico.\n- **Interpretação:** Permite monitorar a frequência de execução de jobs e identificar possíveis picos de utilização.\n\n#### 1.4 Job com maior tempo de execução\n- **Descrição:** Exibe os jobs com maior tempo de execução.\n- **Interpretação:** Jobs com maior tempo de execução podem ser candidatos para otimização.\n\n#### 1.5 % JOBS\n- **Descrição:** Exibe a porcentagem de jobs bem-sucedidos em comparação com os que falharam.\n- **Interpretação:** Um baixo percentual de sucesso pode indicar a necessidade de ajustes no pipeline.\n\n#### 1.6 Jobs com maior índice de falhas\n- **Descrição:** Exibe os jobs com maior número de falhas.\n- **Interpretação:** Jobs com falhas recorrentes devem ser analisados e corrigidos para melhorar a confiabilidade do pipeline.\n\n#### 1.7 Tempo médio de JOB\n- **Descrição:** Mede o tempo médio de execução dos jobs.\n- **Interpretação:** Um aumento no tempo médio pode indicar gargalos ou ineficiências que precisam ser investigadas.\n\n#### 1.8 RUNS POR RUNNERS #\n- **Descrição:** Exibe o número de jobs executados por cada runner.\n- **Interpretação:** Permite monitorar a carga de trabalho de cada runner e identificar possíveis sobrecargas ou quais são mais utilizados.\n\n#### 1.9 TOP jobs com sucesso\n- **Descrição:** Lista os jobs que mais tiveram sucesso nas execuções.\n- **Interpretação:** Ajuda a identificar quais jobs são mais estáveis e confiáveis.\n\n#### 1.10 JOBS COMPLETADOS COM SUCESSO #\n- **Descrição:** Exibe o número de jobs que foram completados com sucesso.\n- **Interpretação:** Um número alto de completamentos bem-sucedidos é um indicador positivo da estabilidade do pipeline.\n\n#### 1.11 RUNNING, FAILED OU NÃO COMPLETADOS #\n- **Descrição:** Exibe o status atual dos jobs, se estão em execução, falharam ou não foram completados.\n- **Interpretação:** Acompanhar esses estados ajuda a garantir que os jobs estão sendo processados corretamente. É possivel acompanhar e ser direcionado diretamente pelo ID da pipeline até a URI referente ao JOB do Gitlab.\n\n#### 1.12 Execuções de jobs por período\n- **Descrição:** Exibe o número de execuções de jobs em um período de tempo especificado.\n- **Interpretação:** Pode ser usado para avaliar a demanda por execução de jobs ao longo do tempo.\n\n### <span style=\"color:yellow\">2. PIPELINES \\#</span>\n\n#### 2.1 PIPELINES POR PERÍODO #\n- **Descrição:** Exibe o número de pipelines executados em um período de tempo específico.\n- **Interpretação:** Ajuda a monitorar a frequência de execução de pipelines ao longo do tempo.\n\n#### 2.2 % de falha e sucesso em execução de build\n- **Descrição:** Exibe a porcentagem de builds bem-sucedidas em comparação com as falhadas.\n- **Interpretação:** Um percentual elevado de falhas pode indicar problemas nos scripts de build ou até mesmo na qualidade de desenvolvimento.\n\n#### 2.3 10 mais stages de build que falharam\n- **Descrição:** Lista os 10 stages de build com o maior número de falhas.\n- **Interpretação:** Identifica quais stages de build que podem precisar de revisão e otimização.\n\n#### 2.4 PIPELINES TOTAL #\n- **Descrição:** Exibe o número total de pipelines executadas.\n- **Interpretação:** O número total de pipelines pode refletir a carga geral de trabalho no ambiente CI/CD.\n\n#### 2.5 PIPELINES FALHAS #\n- **Descrição:** Exibe o número de pipelines que falharam.\n- **Interpretação:** Um número alto de pipelines com falha pode indicar problemas sistêmicos ou de configuração, ou de templates, definição ou qualidade de codigo.\n\n#### 2.6 Tempo médio das Pipelines mais demoradas\n- **Descrição:** Exibe o tempo médio de execução das pipelines que levam mais tempo para completar.\n- **Interpretação:** Pipelines com tempos elevados podem ser candidatas para otimização.\n\n#### 2.7 Execuções de pipelines por período\n- **Descrição:** Exibe o número de pipelines executadas em um período de tempo especificado.\n- **Interpretação:** Permite avaliar a demanda por execução de pipelines ao longo do tempo.\n\n### <span style=\"color:yellow\">3. ENVIRONMENTS \\#</span>\n\n#### 3.1 ENVIRONMENTS\n- **Descrição:** Exibe os detalhes dos environments, como o nome, ID e status das execuções.\n- **Interpretação:** Permite acompanhar os deployments realizados em diferentes environments, exibindo informações relevantes como ids, commits, enviroments, status, etc.\n\n#### 3.2 DEPLOYMENTS POR PERÍODO #\n- **Descrição:** Exibe o número de deploys realizados em um período específico.\n- **Interpretação:** Ajuda a monitorar a frequência de deploys por periodo de visualização.\n\n#### 3.3 DEPLOYS COM FALHA #\n- **Descrição:** Exibe o número de deploys que falharam.\n- **Interpretação:** Um alto número de deploys com falha pode indicar problemas no código ou na configuração da infraestrutura.\n\n#### 3.4 DEPLOYS COM SUCESSO #\n- **Descrição:** Exibe o número de deploys realizados com sucesso.\n- **Interpretação:** Um número alto de deploys bem-sucedidos é um bom indicador da estabilidade do processo de deploy.\n\n#### 3.7 Projetos com maiores atrasos nas entregas (Commits que não foram para deploy)\n- **Descrição:** Este painel mostra os projetos com maior quantidade de commits que ainda não foram enviados para o ambiente de deploy.\n- **Interpretação:** A presença de muitos commits que ainda não foram para o deploy pode indicar problemas no fluxo de entrega contínua. Isso pode causar atrasos no ciclo de desenvolvimento, afetando o tempo de lançamento de novas funcionalidades ou correções de bugs.\n\n#### 3.7 PROJETOS COM ATRASO (Commits sem deploys)\n- **Descrição:** Exibe os projetos que possuem commits que ainda não foram enviados para o ambiente de deploy.\n- **Interpretação:** Um alto número de commits sem deploy pode indicar problemas na entrega contínua ou no processo de integração. Isso pode resultar em atrasos na liberação de funcionalidades ou correções, impactando o ciclo de desenvolvimento.\n\n#### 3.5 Tempo médio de Deployment\n- **Descrição:** Mede o tempo médio de execução dos deploys.\n- **Interpretação:** Um aumento no tempo médio de deploy pode sugerir problemas de performance ou complexidade.\n\n#### 3.6 DEPLOYS POR DEV\n- **Descrição:** Exibe a quantidade de deploys realizados por cada desenvolvedor.\n- **Interpretação:** Ajuda a identificar quem está mais envolvido no processo de entrega."
     }
    }
   ]
  },
  {
   "title": "JOBS #",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JOBS POR PERIODO #",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_ci_pipeline_job_run_count{project=~\"$projeto\", ref=~\"$branch\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Tempo medio de JOB",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(gitlab_ci_pipeline_job_duration_seconds{project=~\"${projeto}.*\", ref=~\"${branch}.*\"} > 0)"
      }
     ]
    },
    {
     "title": "Job com maior tempo de execução",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 15, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, max by (job_name, project) (gitlab_ci_pipeline_job_duration_seconds{project=~\"${projeto}.*\", ref=~\"${branch}\"} > 1))",
       "legendFormat": "{{job_name}} - {{project}}"
      }
     ]
    },
    {
     "title": "% JOBS",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status)(\r\n  gitlab_ci_pipeline_job_status{project=~\"${projeto}.*\",status=\"failed\", ref=~\"${branch}\"}\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (status)(\r\n  gitlab_ci_pipeline_job_status{project=~\"${projeto}.*\",status=\"success\"}\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (status)(\r\n  gitlab_ci_pipeline_job_status{project=~\"${projeto}.*\",status!~\"success|failed|skipped|manual|created\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Jobs com maior indice de falhas",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 16, "x": 8, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum by (project, job_name) (\r\n  gitlab_ci_pipeline_job_status{status=\"failed\", project=~\"${projeto}.*\", ref=~\"${branch}\"}\r\n))) > 2\r\n",
       "legendFormat": "{{project}} - {{job_name}}"
      }
     ]
    },
    {
     "title": "EXECUÇÔES POR TAGS #",
     "type": "barchart",
     "description": "Exibe o número total de execuções de pipelines no projeto especificado. O painel usa a métrica gitlab_ci_pipeline_run_count e conta quantas execuções de pipelines ocorreram, filtrando pelo label project. A visualização mostra esse valor como uma única métrica, destacando-o de forma visual com fundo colorido.\n\nDados nulos podem ser linux ou python. Verificar",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (tag_list) (gitlab_ci_pipeline_job_status{project=~\"${projeto}\", ref=~\"${branch}\"}))\r\n",
       "legendFormat": "{{}}"
      }
     ]
    },
    {
     "title": "EXECUÇÔES POR RUNNERS #",
     "type": "barchart",
     "description": "Exibe o número total de execuções de pipelines no projeto especificado. O painel usa a métrica gitlab_ci_pipeline_run_count e conta quantas execuções de pipelines ocorreram, filtrando pelo label project. A visualização mostra esse valor como uma única métrica, destacando-o de forma visual com fundo colorido.\n\nDados nulos podem ser linux ou python. Verificar",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (runner_description) (gitlab_ci_pipeline_job_status{project=~\"${projeto}\", ref=~\"${branch}\"}))\r\n",
       "legendFormat": "{{}}"
      }
     ]
    },
    {
     "title": "TOP jobs com sucesso",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 16, "x": 8, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum by (project, job_name) (\r\n  gitlab_ci_pipeline_job_status{status=\"success\", project=~\"${projeto}\"}\r\n))) > 0\r\n",
       "legendFormat": "{{project}} - {{job_name}}"
      }
     ]
    },
    {
     "title": "RUNNING, FAILED OU NÂO COMPLETADOS #",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "-max(time() - gitlab_ci_pipeline_job_timestamp{project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, job_name, kind) unless max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, job_name, kind) > 0"
      },
      {
       "expr": "max(gitlab_ci_pipeline_job_duration_seconds{project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, job_name, kind) unless (max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, job_name, kind) > 0)"
      },
      {
       "expr": "max(gitlab_ci_pipeline_job_status{project=~\"${projeto}\", ref=~\"${branch}\", status=~\"running|failed|canceled|created|waiting_for_resource|preparing|pending|skipped|manual|scheduled\"}) \nby (project, ref, job_name, kind, status)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(gitlab_ci_pipeline_job_id{project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, kind, job_name) unless (max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, kind, job_name) > 0)"
      }
     ]
    },
    {
     "title": "JOBS COMPLETADOS COM SUCESSO #",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "-max(time() - gitlab_ci_pipeline_job_timestamp{project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, job_name, kind) \r\nunless max(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"${projeto}\", ref=~\"$REF\"}) by (project, ref, job_name, kind) > 0\r\n\r\n\r\n"
      },
      {
       "expr": "max(gitlab_ci_pipeline_job_duration_seconds{project=~\"${projeto}\", ref=~\"${branch}\", job_name=~\"${branch}\"}) \r\nby (project, ref, job_name, kind)\r\n"
      },
      {
       "expr": "max(gitlab_ci_pipeline_job_id{project=~\"${projeto}\", ref=~\"${branch}\", job_name=~\"${branch}\"}) \r\nby (project, ref, kind, job_name)\r\n\r\n"
      }
     ]
    },
    {
     "title": "Execuções de jobs por periodo",
     "type": "grafana-polystat-panel",
     "description": "Jobs executados na linha do tempo por periodo",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum by (project, job_name) (\r\n  increase(gitlab_ci_pipeline_job_run_count{project=~\".*\", ref=~\".*\"}[$__range])\r\n) > 0\r\n",
       "legendFormat": "{{project}} - {{job_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PIPELINE #",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "PIPELINES POR PERIODO #",
     "type": "stat",
     "description": "Exibe o número de pipelines executados em um período de tempo específico.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_ci_pipeline_run_count{project=~\"$projeto\", ref=~\"$branch\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Tempo medio de Pipeline",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(gitlab_ci_pipeline_duration_seconds{project=~\"${projeto}.*\", ref=~\"${branch}.*\"} > 0)"
      }
     ]
    },
    {
     "title": "Pipelines com maior tempo de execução",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 14, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, max by (project) (gitlab_ci_pipeline_duration_seconds{project=~\"${projeto}.*\", ref=~\"${branch}\"} > 1))",
       "legendFormat": "{{{project}}"
      }
     ]
    },
    {
     "title": "% de falha e sucesso em pipelines",
     "type": "piechart",
     "description": "Exibe o número de pipelines executados em um período de tempo específico.",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gitlab_ci_pipeline_status{status=\"failed\", project=~\"${projeto}.*\", ref=~\"${branch}\"}) by (status)\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(gitlab_ci_pipeline_status{status=\"success\", project=~\"${projeto}.*\", ref=~\"${branch}\"}) by (status)\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(gitlab_ci_pipeline_status{status!~\"success|failed|manual|skipped\", project=~\"${projeto}.*\", ref=~\"${branch}\"}) by (status)\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "10 mais stages de build que falharam",
     "type": "bargauge",
     "description": "Lista os 10 stages de build com o maior número de falhas.",
     "gridPos": { "h": 20, "w": 14, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum by (project, job_name) (\r\n  gitlab_ci_pipeline_job_status{status=\"failed\", project=~\"${projeto}.*\", ref=~\"${branch}\"}\r\n))) > 0\r\n",
       "legendFormat": "{{project}} - {{job_name}}"
      }
     ]
    },
    {
     "title": "RODANDO, COM FALHA OU INCOMPLETO",
     "type": "table",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "-max(time() - gitlab_ci_pipeline_timestamp{project=~\"${projeto}\", ref=~\"${branch}\"}) by (project, ref, kind) unless max(gitlab_ci_pipeline_status{status=~\"success\", project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) > 0"
      },
      {
       "expr": "max(gitlab_ci_pipeline_duration_seconds{project=~\"${projeto}\", ref=~\"$branch\"}) by (project, ref, kind) unless (max(gitlab_ci_pipeline_status{status=~\"success\", project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) > 0)"
      },
      {
       "expr": "(max(gitlab_ci_pipeline_status{project=~\"${projeto}\", ref=~\"$branch\", status=~\"running\"}) by (project, ref, kind) * 2) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"failed\"}) by (project, ref, kind) * 3) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"canceled\"}) by (project, ref, kind) * 4) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"created\"}) by (project, ref, kind) * 5) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"waiting_for_resource\"}) by (project, ref, kind) * 6) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"preparing\"}) by (project, ref, kind) * 7) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"pending\"}) by (project, ref, kind) * 8) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"skipped\"}) by (project, ref, kind) * 9) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"manual\"}) by (project, ref, kind) * 10) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\"$projeto\", ref=~\"$branch\", status=~\"scheduled\"}) by (project, ref, kind) * 11) > 0"
      },
      {
       "expr": "max(gitlab_ci_pipeline_id{project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind, job_name) unless (max(gitlab_ci_pipeline_status{status=~\"success\", project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind, job_name) > 0)"
      }
     ]
    },
    {
     "title": "PIPELINES COMPLETADAS COM SUCESSO",
     "type": "table",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "-max(time() - gitlab_ci_pipeline_timestamp{project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) unless max(gitlab_ci_pipeline_status{status!~\"success\", project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) > 0"
      },
      {
       "expr": "max(gitlab_ci_pipeline_duration_seconds{project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) unless (max(gitlab_ci_pipeline_status{status!~\"success\", project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) > 0)"
      },
      {
       "expr": "max(gitlab_ci_pipeline_id{project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) unless (max(gitlab_ci_pipeline_status{status!~\"success\", project=~\"$projeto\", ref=~\"$branch\"}) by (project, ref, kind) > 0)"
      }
     ]
    },
    {
     "title": "MAIORES ARTEFATOS",
     "type": "table",
     "gridPos": { "h": 15, "w": 9, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk(10, max by (job_name, project, tag_list) (gitlab_ci_pipeline_job_artifact_size_bytes{project=~\"${projeto}\", ref=~\"${branch}\"}))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "stages com sucesso",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 14, "x": 9, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum by (project, job_name) (\r\n  gitlab_ci_pipeline_job_status{status=\"success\", project=~\"${projeto}.*\", ref=~\"${branch}\"} \r\n))) > 1\r\n",
       "legendFormat": "{{project}} - {{job_name}}"
      }
     ]
    },
    {
     "title": "mais stages de build que falharam",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 14, "x": 9, "y": 75 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum by (project, job_name) (\r\n  gitlab_ci_pipeline_job_status{status=\"failed\", job_name=~\".*build.*|.*BUILD.*\", project=~\"${projeto}.*\", ref=~\"${branch}\"}\r\n))) > 0 \r\n",
       "legendFormat": "{{project}} - {{job_name}}"
      }
     ]
    },
    {
     "title": "Projetos executados por periodo",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_ci_pipeline_run_count{proeject=~\"$projeto\",ref=~\"$branch\"}[$__range])) by (project, ref) > 1\r\n",
       "legendFormat": "{{project}} - {{ref}}"
      }
     ]
    },
    {
     "title": "Execuções de pipelines por periodo",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "sum by (project) (\r\n  increase(gitlab_ci_pipeline_run_count{project=~\".*\", ref=~\".*\"}[$__rate_interval])\r\n) > 0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Projetos com falha por periodo",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
     "targets": [
      {
       "expr": "gitlab_ci_pipeline_status{status=\"failed\"} > 0",
       "legendFormat": "{{project}} - {{status}}"
      }
     ]
    },
    {
     "title": "Lead time das pipelines",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, avg by (pipeline_name, project) (gitlab_ci_pipeline_duration_seconds{source=\"push\", project=~\"${projeto}.*\", ref=~\"${branch}\"}))",
       "legendFormat": "{{pipeline_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DEPLOYMENTS ENVIROMENTS #",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEPLOYMENTS POR PERIODO#",
     "type": "stat",
     "description": "Exibe o número de deploys realizados em um período específico.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_ci_environment_deployment_count{project=~\"$projeto\", ref=~\"$branch\", environment=~\"${ENVIRONMENT}\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Tempo medio de Deployment",
     "type": "stat",
     "description": "Mede o tempo médio de execução dos deploys.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(gitlab_ci_environment_deployment_duration_seconds{project=~\"${projeto}.*\", environment=~\"${ENVIRONMENT}\"} > 0)"
      }
     ]
    },
    {
     "title": "PROJETOS COM ATRASO (Commits sem deploys)",
     "type": "stat",
     "description": "Exibe os projetos que possuem commits que ainda não foram enviados para o ambiente de deploy.",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(gitlab_ci_environment_behind_commits_count{project=~\"${projeto}\", environment=~\"$ENVIRONMENT.*\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Projetos com maiores atrasos nas entregas (Commits que não foram para deploy)",
     "type": "bargauge",
     "description": "Este painel mostra os projetos com maior quantidade de commits que ainda não foram enviados para o ambiente de deploy.",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, gitlab_ci_environment_behind_commits_count{project=~\"${projeto}.*\", environment=~\"${ENVIRONMENT}.*\"} > 0)\r\n",
       "legendFormat": "{{project}}"
      }
     ]
    },
    {
     "title": "% DEPLOYS #",
     "type": "piechart",
     "description": "Exibe o número total de execuções de pipelines no projeto especificado. O painel usa a métrica gitlab_ci_pipeline_run_count e conta quantas execuções de pipelines ocorreram, filtrando pelo label project. A visualização mostra esse valor como uma única métrica, destacando-o de forma visual com fundo colorido.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (status) (\r\n  gitlab_ci_environment_deployment_status{project=~\"${projeto}\", environment=~\"${ENVIRONMENT}.*\", status=\"success\"}\r\n) or vector(0)\r\n",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "count by (status) (\r\n  gitlab_ci_environment_deployment_status{project=~\"${projeto}\", environment=~\"${ENVIRONMENT}.*\", status=\"failed\"}\r\n)\r\n",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "%  execuçãode deployments",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gitlab_ci_environment_deployment_status{project=~\"${projeto}.*\", ref=~\"${branch}\", environment=~\".*prd.*|.*PRD.*|.*prod.*|.*PROD.*\"}) by (status, environment)",
       "legendFormat": "PRD"
      },
      {
       "expr": "sum by (environment) (\r\n  sum(gitlab_ci_environment_deployment_status{project=~\"${projeto}.*\", ref=~\"${branch}\", environment=~\".*uat.*|.*qa.*|.*hml.*|.*HML.*|.*HOM.*|.*hom.*\"}) by (status, environment)\r\n)\r\n",
       "legendFormat": "HML"
      },
      {
       "expr": "sum(gitlab_ci_environment_deployment_status{project=~\"${projeto}.*\", ref=~\"${branch}\", environment=~\".*dev.*|.*DEV.*|.*des.*|.*DES.*\"}) by (status, environment)",
       "legendFormat": "DEV"
      },
      {
       "expr": "sum(gitlab_ci_environment_deployment_status{project=~\"${projeto}.*\", ref=~\"${branch}\", environment=~\".*stg.*|.*STG.*|.*stag.*|.*STAG.*\"}) by (status, environment)",
       "legendFormat": "STG"
      },
      {
       "expr": "sum(gitlab_ci_environment_deployment_status{project=~\"${projeto}.*\", ref=~\"${branch}\", environment!~\".*stg.*|.*STG.*|.*stag.*|.*STAG.*|.*dev.*|.*DEV.*|.*des.*|.*DES.*|.*uat.*|.*qa.*|.*hml.*|.*HML.*|.*HOM.*|.*hom.*|.*prd.*|.*PRD.*|.*prod.*|.*PROD.*\"}) by (status, environment)",
       "legendFormat": "OUTROS"
      }
     ]
    },
    {
     "title": "DEPLOYMENTS POR PERIODO#",
     "type": "grafana-polystat-panel",
     "description": "Exibe o número de deploys realizados em um período específico.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_ci_environment_deployment_count{project=~\"$projeto\", ref=~\"$branch\", environment=~\"${ENVIRONMENT}\"}[$__range])) > 0"
      }
     ]
    },
    {
     "title": "DEPLOYS POR DEV",
     "type": "stat",
     "gridPos": { "h": 5, "w": 23, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (username) (\r\n  gitlab_ci_environment_information{project=~\"${projeto}.*\", environment=~\"${ENVIRONMENT}\"}\r\n)\r\n",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "DEPLOYMENTS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_ci_environment_deployment_count{project=~\"${projeto}\",environment=~\"$ENVIRONMENT\"}[$__range])) by (project, environment) / sum(increase(gitlab_ci_environment_deployment_count{project=~\"$projeto\",environment=~\"$ENVIRONMENT\"}[$__range])) by (project, environment) > 0 or vector(0)",
       "legendFormat": "{{ environment }} - {{ project }}"
      }
     ]
    },
    {
     "title": "ENVIRONMENTS",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "(max(gitlab_ci_environment_deployment_status{project=~\"$projeto\", environment=~\"$ENVIRONMENT\", status=~\"success\"}) by (project, environment) * 1) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$projeto\", environment=~\"$ENVIRONMENT\", status=~\"running\"}) by (project, environment) * 2) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$projeto\", environment=~\"$ENVIRONMENT\", status=~\"failed\"}) by (project, environment) * 3) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$projeto\", environment=~\"$ENVIRONMENT\", status=~\"canceled\"}) by (project, environment) * 4) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$projeto\", environment=~\"$ENVIRONMENT\", status=~\"skipped\"}) by (project, environment) * 5) > 0 or\n(max(gitlab_ci_environment_deployment_status{project=~\"$projeto\", environment=~\"$ENVIRONMENT\", status=~\"created|waiting_for_resource|preparing|pending|manual|scheduled\"}) by (project, environment) * 6) > 0"
      },
      {
       "expr": "-max(time() - gitlab_ci_environment_deployment_timestamp{project=~\"$projeto\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
      },
      {
       "expr": "max(gitlab_ci_environment_deployment_duration_seconds{project=~\"$projeto\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
      },
      {
       "expr": "max(gitlab_ci_environment_information{project=~\"$projeto\", environment=~\"$ENVIRONMENT\"}) by (environment_id, project, environment, author_email, current_commit_short_id, ref, latest_commit_short_id)"
      },
      {
       "expr": "max(gitlab_ci_environment_behind_commits_count{project=~\"$projeto\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
      },
      {
       "expr": "max(gitlab_ci_environment_behind_duration_seconds{project=~\"$projeto\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
      },
      {
       "expr": "max(gitlab_ci_environment_deployment_job_id{project=~\"$projeto\", environment=~\"$ENVIRONMENT\"}) by (project, environment)"
      }
     ]
    }
   ]
  }
 ]
}